// docs/react-examples/visuals/slot-text/metric.tsx
import { FluxFlex, FluxPane, FluxPaneBody, FluxVisualSlotText } from '@flux-ui/react';
import { useState, useEffect } from 'react';
export default function Example() {
    const [count, setCount] = useState(12483);
    const value = count.toLocaleString('en-US');
    useEffect(() => {
        const timer = setInterval(
            () => setCount((current) => current + Math.floor(Math.random() * 25) - 8),
            2000
        );
        return () => clearInterval(timer);
    }, []);
    return (
        <>
            <FluxPane style={{ width: '261px' }}>
                <FluxPaneBody>
                    <FluxFlex align={'start'} direction={'vertical'} gap={3}>
                        <span
                            style={{
                                color: 'var(--foreground-secondary)',
                                fontSize: '13px',
                                fontWeight: '500'
                            }}
                        >
                            {'Active users'}
                        </span>
                        <FluxVisualSlotText direction="up" text={value}
                            style={{
                                fontSize: '33px',
                                fontWeight: '700',
                                fontVariantNumeric: 'tabular-nums'
                            }}
                        />
                    </FluxFlex>
                </FluxPaneBody>
            </FluxPane>
        </>
    );
}

// docs/code/visuals/slot-text/metric.vue
<template>
    <FluxPane style="width: 261px;">
        <FluxPaneBody>
            <FluxFlex
                align="start"
                direction="vertical"
                :gap="3">
                <span style="color: var(--foreground-secondary); font-size: 13px; font-weight: 500;">Active users</span>

                <FluxVisualSlotText
                    direction="up"
                    :text="value"
                    style="font-size: 33px; font-weight: 700; font-variant-numeric: tabular-nums;"/>
            </FluxFlex>
        </FluxPaneBody>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxFlex, FluxPane, FluxPaneBody } from '@flux-ui/components';
    import { FluxVisualSlotText } from '@flux-ui/visuals';
    import { onBeforeUnmount, onMounted, ref } from 'vue';

    const count = ref(12483);
    const value = ref(count.value.toLocaleString('en-US'));

    let timer: number;

    onMounted(() => {
        timer = window.setInterval(tick, 2000);
    });

    onBeforeUnmount(() => window.clearInterval(timer));

    function tick(): void {
        count.value += Math.floor(Math.random() * 25) - 8;
        value.value = count.value.toLocaleString('en-US');
    }
</script>
