// docs/react-examples/playground/real-world/ServiceDesk.tsx
import { useState } from 'react';
import {
    FluxBadge,
    FluxIcon,
    FluxItem,
    FluxItemActions,
    FluxItemContent,
    FluxItemMedia,
    FluxItemStack,
    FluxPane,
    FluxPaneBody,
    FluxPaneHeader,
    FluxSpeedDial,
    FluxSpeedDialAction,
    FluxText,
    showSnackbar,
    type FluxColor,
    type FluxIconName
} from '@flux-ui/react';
import { useRef } from 'react';
import { clsx } from 'clsx';
import $style from './ServiceDesk-0.module.scss';
export default function Example() {
    type RequestKind = 'request' | 'incident' | 'visit';
    type WorkRequest = {
        readonly id: number;
        readonly reference: string;
        readonly title: string;
        readonly location: string;
        readonly kind: string;
        readonly icon: FluxIconName;
        readonly color: FluxColor;
    };
    const REQUEST_TYPES: Record<
        RequestKind,
        Pick<WorkRequest, 'title' | 'kind' | 'icon' | 'color'>
    > = {
        request: {
            title: 'Replace the reception door closer',
            kind: 'Request',
            icon: 'screwdriver-wrench',
            color: 'info'
        },
        incident: {
            title: 'Water leak in the loading bay',
            kind: 'Incident',
            icon: 'triangle-exclamation',
            color: 'danger'
        },
        visit: {
            title: 'Inspect emergency lighting',
            kind: 'Site visit',
            icon: 'calendar',
            color: 'gray'
        }
    };
    const [requests, setRequests] = useState<WorkRequest[]>([
        {
            id: 2481,
            reference: 'WO-2481',
            title: 'Replace lighting in the north hall',
            location: 'North hall',
            kind: 'Request',
            icon: 'screwdriver-wrench',
            color: 'info'
        },
        {
            id: 2482,
            reference: 'WO-2482',
            title: 'Loading gate does not close',
            location: 'Gate 4',
            kind: 'Incident',
            icon: 'triangle-exclamation',
            color: 'danger'
        },
        {
            id: 2483,
            reference: 'WO-2483',
            title: 'Quarterly safety inspection',
            location: 'Warehouse',
            kind: 'Site visit',
            icon: 'calendar',
            color: 'gray'
        }
    ]);
    const nextId = useRef(2484);
    function addRequest(kind: RequestKind): void {
        const id = nextId.current++;
        const request = {
            ...REQUEST_TYPES[kind],
            id,
            reference: `WO-${id}`,
            location: 'North depot'
        };
        setRequests([request, ...requests]);
        showSnackbar({
            color: 'success',
            icon: 'circle-check',
            message: `${request.reference} added to the queue.`
        });
    }
    return (
        <>
            <div className="react-example-1v4fr7vixzdvt" style={{ width: '100%' }}>
                <FluxPane>
                    <FluxPaneHeader
                        icon={'clipboard'}
                        subtitle={'North depot · Facilities team'}
                        title={'Incoming work'}
                        after={
                            <>
                                <FluxBadge label={`${requests.length} open`}></FluxBadge>
                            </>
                        }
                    ></FluxPaneHeader>
                    <FluxPaneBody className={clsx($style.serviceDeskFrame)}>
                        <FluxItemStack aria-live={'polite'}>
                            {requests.map((request) => (
                                <FluxItem key={request.id}>
                                    <FluxItemMedia isCenter>
                                        <FluxIcon name={request.icon} size={18}></FluxIcon>
                                    </FluxItemMedia>
                                    <FluxItemContent>
                                        <FluxText weight={600}>{request.title}</FluxText>
                                        <FluxText color={'muted'} size={'small'}>
                                            {request.reference}
                                            {' · '}
                                            {request.location}
                                        </FluxText>
                                    </FluxItemContent>
                                    <FluxItemActions>
                                        <FluxBadge
                                            color={request.color}
                                            label={request.kind}
                                        ></FluxBadge>
                                    </FluxItemActions>
                                </FluxItem>
                            ))}
                        </FluxItemStack>
                        <FluxSpeedDial label={'Create work'}>
                            <FluxSpeedDialAction
                                icon={'file-plus'}
                                label={'New request'}
                                onClick={() => {
                                    addRequest('request');
                                }}
                            ></FluxSpeedDialAction>
                            <FluxSpeedDialAction
                                icon={'triangle-exclamation'}
                                label={'Report incident'}
                                onClick={() => {
                                    addRequest('incident');
                                }}
                            ></FluxSpeedDialAction>
                            <FluxSpeedDialAction
                                icon={'calendar'}
                                label={'Plan site visit'}
                                onClick={() => {
                                    addRequest('visit');
                                }}
                            ></FluxSpeedDialAction>
                        </FluxSpeedDial>
                    </FluxPaneBody>
                </FluxPane>
            </div>
        </>
    );
}

// docs/code/playground/real-world/ServiceDesk.vue
<template>
    <FluxPane>
        <FluxPaneHeader
            icon="clipboard"
            subtitle="North depot · Facilities team"
            title="Incoming work">
            <template #after>
                <FluxBadge :label="`${requests.length} open`"/>
            </template>
        </FluxPaneHeader>

        <FluxPaneBody :class="$style.serviceDeskFrame">
            <FluxItemStack aria-live="polite">
                <FluxItem
                    v-for="request of requests"
                    :key="request.id">
                    <FluxItemMedia is-center>
                        <FluxIcon
                            :name="request.icon"
                            :size="18"/>
                    </FluxItemMedia>

                    <FluxItemContent>
                        <FluxText :weight="600">{{ request.title }}</FluxText>
                        <FluxText
                            color="muted"
                            size="small">
                            {{ request.reference }} · {{ request.location }}
                        </FluxText>
                    </FluxItemContent>

                    <FluxItemActions>
                        <FluxBadge
                            :color="request.color"
                            :label="request.kind"/>
                    </FluxItemActions>
                </FluxItem>
            </FluxItemStack>

            <FluxSpeedDial label="Create work">
                <FluxSpeedDialAction
                    icon="file-plus"
                    label="New request"
                    @click="addRequest('request')"/>
                <FluxSpeedDialAction
                    icon="triangle-exclamation"
                    label="Report incident"
                    @click="addRequest('incident')"/>
                <FluxSpeedDialAction
                    icon="calendar"
                    label="Plan site visit"
                    @click="addRequest('visit')"/>
            </FluxSpeedDial>
        </FluxPaneBody>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxBadge, FluxIcon, FluxItem, FluxItemActions, FluxItemContent, FluxItemMedia, FluxItemStack, FluxPane, FluxPaneBody, FluxPaneHeader, FluxSpeedDial, FluxSpeedDialAction, FluxText, showSnackbar } from '@flux-ui/components';
    import type { FluxColor, FluxIconName } from '@flux-ui/types';
    import { ref } from 'vue';

    type RequestKind = 'request' | 'incident' | 'visit';
    type WorkRequest = {
        readonly id: number;
        readonly reference: string;
        readonly title: string;
        readonly location: string;
        readonly kind: string;
        readonly icon: FluxIconName;
        readonly color: FluxColor;
    };

    const REQUEST_TYPES: Record<RequestKind, Pick<WorkRequest, 'title' | 'kind' | 'icon' | 'color'>> = {
        request: {title: 'Replace the reception door closer', kind: 'Request', icon: 'screwdriver-wrench', color: 'info'},
        incident: {title: 'Water leak in the loading bay', kind: 'Incident', icon: 'triangle-exclamation', color: 'danger'},
        visit: {title: 'Inspect emergency lighting', kind: 'Site visit', icon: 'calendar', color: 'gray'}
    };

    const requests = ref<WorkRequest[]>([
        {id: 2481, reference: 'WO-2481', title: 'Replace lighting in the north hall', location: 'North hall', kind: 'Request', icon: 'screwdriver-wrench', color: 'info'},
        {id: 2482, reference: 'WO-2482', title: 'Loading gate does not close', location: 'Gate 4', kind: 'Incident', icon: 'triangle-exclamation', color: 'danger'},
        {id: 2483, reference: 'WO-2483', title: 'Quarterly safety inspection', location: 'Warehouse', kind: 'Site visit', icon: 'calendar', color: 'gray'}
    ]);

    let nextId = 2484;

    function addRequest(kind: RequestKind): void {
        const id = nextId++;
        const request = {...REQUEST_TYPES[kind], id, reference: `WO-${id}`, location: 'North depot'};
        requests.value.unshift(request);

        showSnackbar({
            color: 'success',
            icon: 'circle-check',
            message: `${request.reference} added to the queue.`
        });
    }
</script>

<style
    lang="scss"
    module>
    .serviceDeskFrame {
        position: relative;
        min-height: 345px;
        padding-bottom: 96px;
        // Anchor the fixed dial to this example instead of the viewport.
        transform: translate(0);
    }
</style>
