// docs/code/ai/conversation/manual.vue
<template>
    <div class="stack">
        <div class="frame">
            <FluxAiConversation
                ref="conversation"
                :is-sticky="false">
                <FluxAiMessage
                    v-for="turn of turns"
                    :key="turn"
                    :icon="turn % 2 === 0 ? 'sparkles' : undefined"
                    :role="turn % 2 === 0 ? 'assistant' : 'user'">
                    Turn {{ turn }} of a conversation that never moves on its own.
                </FluxAiMessage>
            </FluxAiConversation>
        </div>

        <FluxButtonStack>
            <FluxSecondaryButton
                label="Add a turn"
                @click="turns.push(turns.length + 1)"/>

            <FluxPrimaryButton
                label="Jump to latest"
                @click="conversation?.scrollToBottom()"/>
        </FluxButtonStack>
    </div>
</template>

<script
    lang="ts"
    setup>
    import { FluxAiConversation, FluxAiMessage } from '@flux-ui/ai';
    import { FluxButtonStack, FluxPrimaryButton, FluxSecondaryButton } from '@flux-ui/components';
    import { ref, useTemplateRef } from 'vue';

    const conversation = useTemplateRef<InstanceType<typeof FluxAiConversation>>('conversation');
    const turns = ref([1, 2, 3, 4, 5, 6, 7, 8]);
</script>

<style
    scoped
    lang="css">
    .stack {
        display: flex;
        width: 100%;
        flex-flow: column;
        gap: 15px;
    }

    .frame {
        display: flex;
        height: 240px;
    }
</style>

// docs/react-examples/ai/conversation/manual.tsx
import { type ComponentRef, useRef, useState } from 'react';
import {
    FluxAiConversation,
    FluxAiMessage,
    FluxButtonStack,
    FluxPrimaryButton,
    FluxSecondaryButton
} from '@flux-ui/react';
import './manual-0.scss';
export default function Example() {
    const conversation = useRef<ComponentRef<typeof FluxAiConversation> | null>(null);
    const [turns, setTurns] = useState([1, 2, 3, 4, 5, 6, 7, 8]);
    return (
        <>
            <div className="react-example-q3uc29w7brrm" style={{ width: '100%' }}>
                <div className={'stack'}>
                    <div className={'frame'}>
                        <FluxAiConversation ref={conversation} isSticky={false}>
                            {turns.map((turn) => (
                                <FluxAiMessage
                                    key={turn}
                                    icon={turn % 2 === 0 ? 'sparkles' : undefined}
                                    role={turn % 2 === 0 ? 'assistant' : 'user'}
                                >
                                    {' Turn '}
                                    {turn}
                                    {' of a conversation that never moves on its own. '}
                                </FluxAiMessage>
                            ))}
                        </FluxAiConversation>
                    </div>
                    <FluxButtonStack>
                        <FluxSecondaryButton
                            label={'Add a turn'}
                            onClick={() => {
                                setTurns([...turns, turns.length + 1]);
                            }}
                        ></FluxSecondaryButton>
                        <FluxPrimaryButton
                            label={'Jump to latest'}
                            onClick={() => {
                                conversation.current?.scrollToBottom();
                            }}
                        ></FluxPrimaryButton>
                    </FluxButtonStack>
                </div>
            </div>
        </>
    );
}
