// docs/react-examples/visuals/highlighter-group/in-view.tsx
import {FluxVisualHighlighter, FluxVisualHighlighterGroup} from '@flux-ui/react';
export default function Example() {
    return <p style={{maxWidth: 429, fontSize: 21, lineHeight: 1.9, textAlign: 'center'}}>
        <FluxVisualHighlighterGroup whenInView>
            This <FluxVisualHighlighter>cascade</FluxVisualHighlighter> starts <FluxVisualHighlighter variant="underline" color="var(--primary-solid)">only</FluxVisualHighlighter> once it scrolls into view.
        </FluxVisualHighlighterGroup>
    </p>;
}

// docs/code/visuals/highlighter-group/in-view.vue
<template>
    <p style="max-width: 429px; font-size: 21px; line-height: 1.9; text-align: center;">
        <FluxVisualHighlighterGroup when-in-view>
            This
            <FluxVisualHighlighter>cascade</FluxVisualHighlighter>
            starts
            <FluxVisualHighlighter
                variant="underline"
                color="var(--primary-solid)">only</FluxVisualHighlighter>
            once it scrolls into view.
        </FluxVisualHighlighterGroup>
    </p>
</template>

<script
    lang="ts"
    setup>
    import { FluxVisualHighlighter, FluxVisualHighlighterGroup } from '@flux-ui/visuals';
</script>
