// docs/react-examples/components/data-table/skeleton.tsx
import { useState } from 'react';
import {
    FluxDataTable,
    FluxPane,
    FluxPaneHeader,
    FluxSecondaryButton,
    FluxSkeleton,
    FluxTableCell,
    FluxTableHeader,
    FluxTableRow
} from '@flux-ui/react';
export default function Example() {
    const people = [
        { id: 1, name: 'Ada Lovelace', role: 'Lead', commits: 1287 },
        { id: 2, name: 'Alan Turing', role: 'Engineer', commits: 942 },
        { id: 3, name: 'Grace Hopper', role: 'Engineer', commits: 1530 },
        { id: 4, name: 'Margaret Hamilton', role: 'Engineer', commits: 2041 }
    ];
    const [isLoading, setIsLoading] = useState(false);
    function refresh(): void {
        setIsLoading(true);
        setTimeout(() => setIsLoading(false), 2000);
    }
    return (
        <>
            <FluxPane>
                <FluxPaneHeader
                    title={'Members'}
                    after={
                        <>
                            <FluxSecondaryButton
                                disabled={isLoading}
                                iconLeading={'rotate'}
                                label={'Refresh'}
                                onClick={refresh}
                            ></FluxSecondaryButton>
                        </>
                    }
                ></FluxPaneHeader>
                <FluxDataTable
                    isLoading={isLoading}
                    items={people}
                    limits={[]}
                    page={1}
                    perPage={4}
                    total={people.length}
                    isHoverable
                    columns={[
                        {
                            key: 'name',
                            header: <>{'Name'}</>,
                            render: (row, rowIndex) => {
                                const slotProps = { item: row, index: rowIndex };
                                const { item } = slotProps;
                                return <>{item.name}</>;
                            }
                        },
                        {
                            key: 'role',
                            header: <>{'Role'}</>,
                            render: (row, rowIndex) => {
                                const slotProps = { item: row, index: rowIndex };
                                const { item } = slotProps;
                                return <>{item.role}</>;
                            }
                        },
                        {
                            key: 'commits',
                            header: <>{'Commits'}</>,
                            isShrinking: true,
                            render: (row, rowIndex) => {
                                const slotProps = { item: row, index: rowIndex };
                                const { item } = slotProps;
                                return <>{item.commits}</>;
                            }
                        }
                    ]}
                    loading={
                        <>
                            {Array.from({ length: 4 }, (_, i) => i + 1).map((row) => (
                                <FluxTableRow key={row}>
                                    {Array.from({ length: 3 }, (_, i) => i + 1).map((cell) => (
                                        <FluxTableCell key={cell}>
                                            <FluxSkeleton></FluxSkeleton>
                                        </FluxTableCell>
                                    ))}
                                </FluxTableRow>
                            ))}
                        </>
                    }
                ></FluxDataTable>
            </FluxPane>
        </>
    );
}

// docs/code/components/data-table/skeleton.vue
<template>
    <FluxPane>
        <FluxPaneHeader title="Members">
            <template #after>
                <FluxSecondaryButton
                    :disabled="isLoading"
                    icon-leading="rotate"
                    label="Refresh"
                    @click="refresh"/>
            </template>
        </FluxPaneHeader>

        <FluxDataTable
            :is-loading="isLoading"
            :items="people"
            :limits="[]"
            :page="1"
            :per-page="4"
            :total="people.length"
            is-hoverable>
            <template #header>
                <FluxTableHeader>Name</FluxTableHeader>
                <FluxTableHeader>Role</FluxTableHeader>
                <FluxTableHeader is-shrinking>Commits</FluxTableHeader>
            </template>

            <template #loading="{perPage}">
                <FluxTableRow
                    v-for="row in perPage"
                    :key="row">
                    <FluxTableCell
                        v-for="cell in 3"
                        :key="cell">
                        <FluxSkeleton/>
                    </FluxTableCell>
                </FluxTableRow>
            </template>

            <template #name="{item}">
                <FluxTableCell>{{ item.name }}</FluxTableCell>
            </template>

            <template #role="{item}">
                <FluxTableCell>{{ item.role }}</FluxTableCell>
            </template>

            <template #commits="{item}">
                <FluxTableCell is-numeric>{{ item.commits }}</FluxTableCell>
            </template>
        </FluxDataTable>
    </FluxPane>
</template>

<script
    setup
    lang="ts">
    import { FluxDataTable, FluxPane, FluxPaneHeader, FluxSecondaryButton, FluxSkeleton, FluxTableCell, FluxTableHeader, FluxTableRow } from '@flux-ui/components';
    import { ref } from 'vue';

    const people = [
        {id: 1, name: 'Ada Lovelace', role: 'Lead', commits: 1287},
        {id: 2, name: 'Alan Turing', role: 'Engineer', commits: 942},
        {id: 3, name: 'Grace Hopper', role: 'Engineer', commits: 1530},
        {id: 4, name: 'Margaret Hamilton', role: 'Engineer', commits: 2041}
    ];

    const isLoading = ref(false);

    function refresh(): void {
        isLoading.value = true;
        setTimeout(() => isLoading.value = false, 2000);
    }
</script>
