// docs/react-examples/flow/examples/running.tsx
import { useState } from 'react';
import {
    FluxBadge,
    FluxFlow,
    FluxFlowActionCard,
    FluxFlowConnection,
    FluxFlowNode,
    FluxFlowPill,
    type FluxColor,
    type FluxIconName
} from '@flux-ui/react';
import { useEffect } from 'react';
export default function Example() {
    const STAGES: {
        readonly id: string;
        readonly icon: FluxIconName;
        readonly title: string;
        readonly subtitle: string;
        readonly description: string;
    }[] = [
        {
            id: 'fetch',
            icon: 'database',
            title: 'Fetch orders',
            subtitle: 'Shopify API',
            description: 'Pulls every order created since the last successful run.'
        },
        {
            id: 'enrich',
            icon: 'wand-magic-sparkles',
            title: 'Enrich records',
            subtitle: 'Customer service',
            description: 'Adds customer, currency and tax data to each order.'
        },
        {
            id: 'load',
            icon: 'server',
            title: 'Load into warehouse',
            subtitle: 'BigQuery',
            description: 'Writes the enriched batch and marks the run as complete.'
        }
    ];
    const STEPS = STAGES.length + 1;
    const STEP_DURATION = 1400;
    const HOLD = 1;
    const IDLE = 0.6;
    const [elapsed, setElapsed] = useState(0);
    let frame = 0;
    function isRunning(step: number): boolean {
        return elapsed >= step && elapsed < step + 1;
    }
    function isDone(step: number): boolean {
        return elapsed >= step + 1;
    }
    function colorOf(step: number): FluxColor {
        if (isDone(step)) {
            return 'success';
        }
        return isRunning(step) ? 'primary' : 'gray';
    }
    function labelOf(step: number): string {
        if (isDone(step)) {
            return 'Done';
        }
        return isRunning(step) ? 'Running' : 'Pending';
    }
    function progressOf(step: number): number {
        return Math.min(Math.max(elapsed - step + 1, 0), 1);
    }
    useEffect(() => {
        (() => {
            const start = performance.now();
            const tick = (now: number) => {
                setElapsed((((now - start) / STEP_DURATION) % (STEPS + HOLD + IDLE)) - IDLE);
                frame = requestAnimationFrame(tick);
            };
            frame = requestAnimationFrame(tick);
        })();
        return () => (() => cancelAnimationFrame(frame))();
    }, []);
    return (
        <>
            <FluxFlow padding={21}>
                <FluxFlowNode id={'trigger'} x={81} y={0}>
                    <FluxFlowPill
                        color={'info'}
                        icon={'bolt'}
                        label={'Nightly sync'}
                        isLoading={isRunning(0)}
                    ></FluxFlowPill>
                </FluxFlowNode>
                {STAGES.map((stage, index) => (
                    <FluxFlowNode key={stage.id} id={stage.id} x={0} y={120 + index * 270}>
                        <FluxFlowActionCard
                            title={stage.title}
                            subtitle={stage.subtitle}
                            icon={isDone(index + 1) ? 'circle-check' : stage.icon}
                            color={colorOf(index + 1)}
                            active={isRunning(index + 1)}
                            isLoading={isRunning(index + 1)}
                            footer={
                                <>
                                    <FluxBadge
                                        color={colorOf(index + 1)}
                                        label={labelOf(index + 1)}
                                    ></FluxBadge>
                                </>
                            }
                        >
                            {stage.description}
                        </FluxFlowActionCard>
                    </FluxFlowNode>
                ))}
                <FluxFlowConnection
                    from={'trigger'}
                    to={'fetch'}
                    fromAlign={'start'}
                    progressColor={'primary'}
                    progressValue={progressOf(1)}
                ></FluxFlowConnection>
                <FluxFlowConnection
                    from={'fetch'}
                    to={'enrich'}
                    progressColor={'primary'}
                    progressValue={progressOf(2)}
                ></FluxFlowConnection>
                <FluxFlowConnection
                    from={'enrich'}
                    to={'load'}
                    progressColor={'primary'}
                    progressValue={progressOf(3)}
                ></FluxFlowConnection>
            </FluxFlow>
        </>
    );
}

// docs/code/flow/examples/running.vue
<template>
    <FluxFlow :padding="21">
        <FluxFlowNode id="trigger" :x="81" :y="0">
            <FluxFlowPill
                color="info"
                icon="bolt"
                label="Nightly sync"
                :is-loading="isRunning(0)"/>
        </FluxFlowNode>

        <FluxFlowNode
            v-for="(stage, index) of STAGES"
            :key="stage.id"
            :id="stage.id"
            :x="0"
            :y="120 + index * 270">
            <FluxFlowActionCard
                :title="stage.title"
                :subtitle="stage.subtitle"
                :icon="isDone(index + 1) ? 'circle-check' : stage.icon"
                :color="colorOf(index + 1)"
                :active="isRunning(index + 1)"
                :is-loading="isRunning(index + 1)">
                {{ stage.description }}

                <template #footer>
                    <FluxBadge
                        :color="colorOf(index + 1)"
                        :label="labelOf(index + 1)"/>
                </template>
            </FluxFlowActionCard>
        </FluxFlowNode>

        <FluxFlowConnection
            from="trigger"
            to="fetch"
            from-align="start"
            progress-color="primary"
            :progress-value="progressOf(1)"/>

        <FluxFlowConnection
            from="fetch"
            to="enrich"
            progress-color="primary"
            :progress-value="progressOf(2)"/>

        <FluxFlowConnection
            from="enrich"
            to="load"
            progress-color="primary"
            :progress-value="progressOf(3)"/>
    </FluxFlow>
</template>

<script
    setup
    lang="ts">
    import type { FluxColor, FluxIconName } from '@flux-ui/types';
    import { FluxBadge } from '@flux-ui/components';
    import { FluxFlow, FluxFlowActionCard, FluxFlowConnection, FluxFlowNode, FluxFlowPill } from '@flux-ui/flow';
    import { onBeforeUnmount, onMounted, ref } from 'vue';

    const STAGES: { readonly id: string; readonly icon: FluxIconName; readonly title: string; readonly subtitle: string; readonly description: string }[] = [
        {id: 'fetch', icon: 'database', title: 'Fetch orders', subtitle: 'Shopify API', description: 'Pulls every order created since the last successful run.'},
        {id: 'enrich', icon: 'wand-magic-sparkles', title: 'Enrich records', subtitle: 'Customer service', description: 'Adds customer, currency and tax data to each order.'},
        {id: 'load', icon: 'server', title: 'Load into warehouse', subtitle: 'BigQuery', description: 'Writes the enriched batch and marks the run as complete.'}
    ];

    // The run walks the pill and the three cards in order: a step runs for one
    // unit of elapsed time, during which the connector towards the next step
    // fills, so a step that starts running is already fully connected.
    const STEPS = STAGES.length + 1;
    const STEP_DURATION = 1400;

    // A finished run holds for a beat, then the canvas clears for a beat before
    // the next one starts, so the reset reads as a reset.
    const HOLD = 1;
    const IDLE = 0.6;

    const elapsed = ref(0);

    let frame = 0;

    onMounted(() => {
        const start = performance.now();

        const tick = (now: number) => {
            elapsed.value = (((now - start) / STEP_DURATION) % (STEPS + HOLD + IDLE)) - IDLE;
            frame = requestAnimationFrame(tick);
        };

        frame = requestAnimationFrame(tick);
    });

    onBeforeUnmount(() => cancelAnimationFrame(frame));

    function isRunning(step: number): boolean {
        return elapsed.value >= step && elapsed.value < step + 1;
    }

    function isDone(step: number): boolean {
        return elapsed.value >= step + 1;
    }

    function colorOf(step: number): FluxColor {
        if (isDone(step)) {
            return 'success';
        }

        return isRunning(step) ? 'primary' : 'gray';
    }

    function labelOf(step: number): string {
        if (isDone(step)) {
            return 'Done';
        }

        return isRunning(step) ? 'Running' : 'Pending';
    }

    function progressOf(step: number): number {
        return Math.min(Math.max(elapsed.value - step + 1, 0), 1);
    }
</script>
