// docs/react-examples/components/filter/custom/MyToggleFilter.tsx
import {defineFilter, FluxMenuGroup, FluxMenuItem, pickFilterCommon, useFilterInjection, type FluxFilterSpec} from '@flux-ui/react';

export default function MyToggleFilter({name}: FluxFilterSpec) {
    const {back, state, setValue} = useFilterInjection();
    function select(value: boolean) {setValue(name, value); back();}
    return <FluxMenuGroup>
        <FluxMenuItem isSelectable isSelected={state[name] === true} label="Enabled" onClick={() => select(true)} />
        <FluxMenuItem isSelectable isSelected={state[name] === false} label="Disabled" onClick={() => select(false)} />
    </FluxMenuGroup>;
}

MyToggleFilter.filterDefinition = defineFilter<FluxFilterSpec>(props => ({
    ...pickFilterCommon(props),
    type: 'toggle',
    async getValueLabel(value) {return value === true ? 'Enabled' : value === false ? 'Disabled' : null;}
}));

// docs/code/components/filter/custom/MyToggleFilter.vue
<template>
    <FluxMenuGroup>
        <FluxMenuItem
            is-selectable
            :is-selected="state[name] === true"
            label="Enabled"
            @click="onSelect(true)"/>

        <FluxMenuItem
            is-selectable
            :is-selected="state[name] === false"
            label="Disabled"
            @click="onSelect(false)"/>
    </FluxMenuGroup>
</template>

<script
    lang="ts"
    setup>
    import { defineFilter, FluxMenuGroup, FluxMenuItem, pickFilterCommon, useFilterInjection } from '@flux-ui/components';
    import type { FluxFilterSpec } from '@flux-ui/types';

    type Props = FluxFilterSpec;

    defineFilter<Props>(p => ({
        ...pickFilterCommon(p),
        type: 'toggle',
        async getValueLabel(value) {
            if (value === true) {
                return 'Enabled';
            }

            if (value === false) {
                return 'Disabled';
            }

            return null;
        }
    }));

    const {
        name
    } = defineProps<Props>();

    const {back, state, setValue} = useFilterInjection();

    function onSelect(value: boolean): void {
        setValue(name, value);
        back();
    }
</script>
