// docs/react-examples/application/top/snippet.tsx
import { FluxApplicationTop, FluxPrimaryButton, FluxTabBarItem } from '@flux-ui/react';
export default function Example() {
    return (
        <>
            <FluxApplicationTop
                icon={'house'}
                title={'Dashboard'}
                end={
                    <>
                        <FluxPrimaryButton iconLeading={'plus'} label={'New'}></FluxPrimaryButton>
                    </>
                }
                tabs={
                    <>
                        <FluxTabBarItem
                            label={'Overview'}
                            to={{ pathname: '/dashboard.overview' }}
                        ></FluxTabBarItem>
                        <FluxTabBarItem
                            label={'Activity'}
                            to={{ pathname: '/dashboard.activity' }}
                        ></FluxTabBarItem>
                    </>
                }
            ></FluxApplicationTop>
        </>
    );
}

// docs/code/application/top/snippet.vue
<template>
    <FluxApplicationTop
        icon="house"
        title="Dashboard">
        <template #end>
            <FluxPrimaryButton
                icon-leading="plus"
                label="New"/>
        </template>

        <template #tabs>
            <FluxTabBarItem
                label="Overview"
                :to="{name: 'dashboard.overview'}"/>

            <FluxTabBarItem
                label="Activity"
                :to="{name: 'dashboard.activity'}"/>
        </template>
    </FluxApplicationTop>
</template>

<script
    setup
    lang="ts">
    import { FluxApplicationTop } from '@flux-ui/application';
    import { FluxPrimaryButton, FluxTabBarItem } from '@flux-ui/components';
</script>
