// docs/code/components/form/date-time/limited.vue
<template>
    <FluxPane style="max-width: 390px">
        <FluxForm>
            <FluxPaneBody>
                <FluxFormField label="Starts on">
                    <FluxFormDateTimeInput
                        v-model="value"
                        :min="min"
                        :max="max"/>
                </FluxFormField>
            </FluxPaneBody>
        </FluxForm>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxForm, FluxFormDateTimeInput, FluxFormField, FluxPane, FluxPaneBody } from '@flux-ui/components';
    import { DateTime } from 'luxon';
    import { ref } from 'vue';

    const min = ref(DateTime.now().startOf('day'));
    const max = ref(DateTime.now().plus({days: 7}).endOf('day'));

    const value = ref(DateTime.now());
</script>

// docs/react-examples/components/form/date-time/limited.tsx
import { type ComponentProps, useState } from 'react';
import { FluxForm, FluxFormDateTimeInput, FluxFormField, FluxPane, FluxPaneBody } from '@flux-ui/react';
import { DateTime } from 'luxon';
export default function Example() {
    const [min, setMin] = useState(DateTime.now().startOf('day'));
    const [max, setMax] = useState(DateTime.now().plus({ days: 7 }).endOf('day'));
    const [value, setValue] = useState<Exclude<ComponentProps<typeof FluxFormDateTimeInput>['value'], undefined>>(DateTime.now());
    return (<><FluxPane style={{ "maxWidth": "390px" }}><FluxForm><FluxPaneBody><FluxFormField label={"Starts on"}><FluxFormDateTimeInput value={value} onValueChange={setValue} min={min} max={max}></FluxFormDateTimeInput></FluxFormField></FluxPaneBody></FluxForm></FluxPane></>);
}
