// docs/react-examples/components/attention/notice/closeable.tsx
import { FluxNotice } from '@flux-ui/react';
import { useEffect, useState } from 'react';
export default function Example() {
    const [isVisible, setVisible] = useState(true);
    useEffect(() => {
        if (isVisible) return;
        const timeout = setTimeout(() => setVisible(true), 3000);
        return () => clearTimeout(timeout);
    }, [isVisible]);
    function onClose() {
        setVisible(false);
    }
    return (
        <>
            {isVisible ? (
                <FluxNotice
                    color={'info'}
                    icon={'circle-info'}
                    message={"You can dismiss this notice when you're done reading it."}
                    isCloseable
                    onClose={onClose}
                ></FluxNotice>
            ) : null}
        </>
    );
}

// docs/code/components/attention/notice/closeable.vue
<template>
    <FluxNotice
        v-if="isVisible"
        color="info"
        icon="circle-info"
        message="You can dismiss this notice when you're done reading it."
        is-closeable
        @close="onClose"/>
</template>

<script
    lang="ts"
    setup>
    import { FluxNotice } from '@flux-ui/components';
    import { onBeforeUnmount, ref } from 'vue';

    const isVisible = ref(true);

    let timeout: ReturnType<typeof setTimeout>;

    onBeforeUnmount(() => clearTimeout(timeout));

    function onClose(): void {
        isVisible.value = false;
        timeout = setTimeout(() => isVisible.value = true, 3000);
    }
</script>
