// docs/react-examples/flow/components/card/loading.tsx
import {
    FluxBadge,
    FluxDescriptionItem,
    FluxDescriptionList,
    FluxFlowActionCard,
    FluxSecondaryButton
} from '@flux-ui/react';
import { useState, useEffect } from 'react';
export default function Example() {
    const [isFinished, setFinished] = useState(false);
    const [isRunning, setRunning] = useState(false);
    useEffect(() => {
        if (!isRunning) return;
        const timeout = setTimeout(() => {
            setFinished(true);
            setRunning(false);
        }, 2400);
        return () => clearTimeout(timeout);
    }, [isRunning]);
    function run() {
        setFinished(false);
        setRunning(true);
    }
    return (
        <>
            <div style={{ display: 'flex', justifyContent: 'center', padding: '12px 0' }}>
                <FluxFlowActionCard
                    title={'Sync inventory'}
                    subtitle={'Warehouse API'}
                    active={isRunning}
                    isLoading={isRunning}
                    footer={
                        <>
                            <FluxSecondaryButton
                                iconLeading={'rotate'}
                                label={'Run step'}
                                disabled={isRunning}
                                onClick={run}
                            ></FluxSecondaryButton>
                            {isFinished ? (
                                <FluxBadge
                                    color={'success'}
                                    icon={'circle-check'}
                                    label={'Synced'}
                                ></FluxBadge>
                            ) : null}
                        </>
                    }
                >
                    <FluxDescriptionList>
                        <FluxDescriptionItem label={'Products'}>{'1.284'}</FluxDescriptionItem>
                        <FluxDescriptionItem label={'Batch size'}>{'250'}</FluxDescriptionItem>
                    </FluxDescriptionList>
                </FluxFlowActionCard>
            </div>
        </>
    );
}

// docs/code/flow/components/card/loading.vue
<template>
    <div style="display: flex; justify-content: center; padding: 12px 0">
        <FluxFlowActionCard
            title="Sync inventory"
            subtitle="Warehouse API"
            :active="isRunning"
            :is-loading="isRunning">
            <FluxDescriptionList>
                <FluxDescriptionItem label="Products">1.284</FluxDescriptionItem>
                <FluxDescriptionItem label="Batch size">250</FluxDescriptionItem>
            </FluxDescriptionList>

            <template #footer>
                <FluxSecondaryButton
                    icon-leading="rotate"
                    label="Run step"
                    :disabled="isRunning"
                    @click="run"/>

                <FluxBadge
                    v-if="isFinished"
                    color="success"
                    icon="circle-check"
                    label="Synced"/>
            </template>
        </FluxFlowActionCard>
    </div>
</template>

<script
    setup
    lang="ts">
    import { FluxBadge, FluxDescriptionItem, FluxDescriptionList, FluxSecondaryButton } from '@flux-ui/components';
    import { FluxFlowActionCard } from '@flux-ui/flow';
    import { onBeforeUnmount, ref } from 'vue';

    const isFinished = ref(false);
    const isRunning = ref(false);

    let timeout = 0;

    onBeforeUnmount(() => clearTimeout(timeout));

    function run(): void {
        isFinished.value = false;
        isRunning.value = true;

        timeout = setTimeout(() => {
            isFinished.value = true;
            isRunning.value = false;
        }, 2400);
    }
</script>
