// docs/code/components/form/date-range/month.vue
<template>
    <FluxPane style="max-width: 390px">
        <FluxForm>
            <FluxPaneBody>
                <FluxFormField label="Month">
                    <FluxFormDateRangeInput
                        v-model="value"
                        range-mode="month"/>
                </FluxFormField>
            </FluxPaneBody>
        </FluxForm>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxForm, FluxFormDateRangeInput, FluxFormField, FluxPane, FluxPaneBody } from '@flux-ui/components';
    import { DateTime } from 'luxon';
    import { ref } from 'vue';

    const value = ref<[DateTime, DateTime] | null>([
        DateTime.now().startOf('month'),
        DateTime.now().endOf('month')
    ]);
</script>

// docs/react-examples/components/form/date-range/month.tsx
import { type ComponentProps, useState } from 'react';
import { FluxForm, FluxFormDateRangeInput, FluxFormField, FluxPane, FluxPaneBody } from '@flux-ui/react';
import { DateTime } from 'luxon';
export default function Example() {
    const [value, setValue] = useState<Exclude<ComponentProps<typeof FluxFormDateRangeInput>['value'], undefined>>([
        DateTime.now().startOf('month'),
        DateTime.now().endOf('month')
    ]);
    return (<><FluxPane style={{ "maxWidth": "390px" }}><FluxForm><FluxPaneBody><FluxFormField label={"Month"}><FluxFormDateRangeInput value={value} onValueChange={setValue} rangeMode={"month"}></FluxFormDateRangeInput></FluxFormField></FluxPaneBody></FluxForm></FluxPane></>);
}
