// docs/code/guide/components/date-picker/week.vue
<template>
    <FluxPane style="width: 330px">
        <FluxDatePicker
            v-model="dates"
            range-mode="week"/>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxDatePicker, FluxPane } from '@flux-ui/flux';
    import { DateTime } from 'luxon';
    import { ref } from 'vue';

    const dates = ref([
        DateTime.now().startOf('week'),
        DateTime.now().endOf('week')
    ]);
</script>

// docs/react-examples/components/form/date-range/week.tsx
import { type ComponentProps, useState } from 'react';
import { FluxForm, FluxFormDateRangeInput, FluxFormField, FluxPane, FluxPaneBody } from '@flux-ui/react';
import { DateTime } from 'luxon';
export default function Example() {
    const [value, setValue] = useState<Exclude<ComponentProps<typeof FluxFormDateRangeInput>['value'], undefined>>([
        DateTime.now().startOf('week'),
        DateTime.now().endOf('week')
    ]);
    return (<><FluxPane style={{ "maxWidth": "390px" }}><FluxForm><FluxPaneBody><FluxFormField label={"Week"}><FluxFormDateRangeInput value={value} onValueChange={setValue} rangeMode={"week"}></FluxFormDateRangeInput></FluxFormField></FluxPaneBody></FluxForm></FluxPane></>);
}
