// docs/react-examples/application/playground/context/LaneMenu.tsx
import {
    FluxApplicationMenuContext,
    FluxMenuGroup,
    FluxMenuItem,
    useRoute,
    useRouter
} from '@flux-ui/react';
export default function Example() {
    const route = useRoute();
    const router = useRouter();
    return (
        <>
            <FluxApplicationMenuContext
                icon={'truck'}
                subtitle={'Rotterdam to Hamburg'}
                title={'Lane RTM-HAM'}
            ></FluxApplicationMenuContext>
            <FluxMenuGroup>
                <FluxMenuItem
                    iconLeading={'gauge'}
                    isActive={route?.fullPath === '/lanes/rtm-ham'}
                    label={'Performance'}
                    onClick={() => {
                        router?.navigate?.('/lanes/rtm-ham');
                    }}
                ></FluxMenuItem>
                <FluxMenuItem
                    iconLeading={'money-bill'}
                    isActive={route?.fullPath === '/lanes/rtm-ham/rates'}
                    label={'Rates'}
                    onClick={() => {
                        router?.navigate?.('/lanes/rtm-ham/rates');
                    }}
                ></FluxMenuItem>
                <FluxMenuItem iconLeading={'calendar'} label={'Departures'}></FluxMenuItem>
                <FluxMenuItem iconLeading={'file-lines'} label={'Documents'}></FluxMenuItem>
            </FluxMenuGroup>
        </>
    );
}

// docs/code/application/playground/context/LaneMenu.vue
<template>
    <FluxApplicationMenuContext
        icon="truck"
        subtitle="Rotterdam to Hamburg"
        title="Lane RTM-HAM"/>

    <FluxMenuGroup>
        <FluxMenuItem
            icon-leading="gauge"
            :is-active="route.name === 'lane'"
            label="Performance"
            @click="router.push({name: 'lane'})"/>

        <FluxMenuItem
            icon-leading="money-bill"
            :is-active="route.name === 'lane.rates'"
            label="Rates"
            @click="router.push({name: 'lane.rates'})"/>

        <FluxMenuItem
            icon-leading="calendar"
            label="Departures"/>

        <FluxMenuItem
            icon-leading="file-lines"
            label="Documents"/>
    </FluxMenuGroup>
</template>

<script
    lang="ts"
    setup>
    import { FluxApplicationMenuContext } from '@flux-ui/application';
    import { FluxMenuGroup, FluxMenuItem } from '@flux-ui/components';
    import { useRoute, useRouter } from 'vue-router';

    const route = useRoute();
    const router = useRouter();
</script>
