// docs/react-examples/components/context-menu/finder.tsx
import { useState } from 'react';
import {
    FluxContextMenu,
    FluxMenu,
    FluxMenuFlyout,
    FluxMenuGroup,
    FluxMenuItem,
    FluxPane,
    FluxSeparator,
    FluxToggle
} from '@flux-ui/react';
export default function Example() {
    const [showCone, setShowCone] = useState(false);
    return (
        <>
            <div style={{ display: 'flex', flexFlow: 'column', gap: '15px' }}>
                <div style={{display: 'flex', alignItems: 'center', gap: 9}}>
                    <FluxToggle checked={showCone} onCheckedChange={setShowCone} />
                    Prediction cone
                </div>
                <FluxContextMenu
                    debugCone={showCone}
                    menu={({ close }) => (
                        <>
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        iconLeading={'arrow-up-right-from-square'}
                                        label={'Open'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuFlyout icon={'image'} label={'Open With'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    iconLeading={'eye'}
                                                    label={'Preview'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'image'}
                                                    label={'Photos'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                            <FluxSeparator></FluxSeparator>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    label={'App Store…'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                    <FluxMenuItem
                                        iconLeading={'trash'}
                                        isDestructive
                                        label={'Move to Trash'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                </FluxMenuGroup>
                                <FluxSeparator></FluxSeparator>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        iconLeading={'circle-info'}
                                        label={'Get Info'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuItem
                                        iconLeading={'pen'}
                                        label={'Rename'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuItem
                                        iconLeading={'clone'}
                                        label={'Duplicate'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuItem
                                        iconLeading={'eye'}
                                        label={'Quick Look'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                </FluxMenuGroup>
                                <FluxSeparator></FluxSeparator>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        iconLeading={'copy'}
                                        label={'Copy'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuFlyout icon={'arrow-up-from-square'} label={'Share'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    iconLeading={'paper-plane'}
                                                    label={'Mail'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'copy'}
                                                    label={'Copy Link'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                    <FluxMenuFlyout icon={'bolt'} label={'Quick Actions'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    iconLeading={'rotate-left'}
                                                    label={'Rotate Left'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'pen'}
                                                    label={'Markup'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'image'}
                                                    label={'Convert Image'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                </FluxMenuGroup>
                                <FluxSeparator></FluxSeparator>
                                <FluxMenuGroup>
                                    <FluxMenuFlyout icon={'palette'} label={'Tags'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    iconLeading={'circle'}
                                                    label={'Red'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'circle'}
                                                    label={'Orange'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'circle'}
                                                    label={'Green'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                    <FluxMenuFlyout icon={'gear'} label={'Services'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    label={'Show in Enclosing Folder'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    label={'New Terminal at Folder'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </>
                    )}
                >
                    <FluxPane style={{ padding: '36px', textAlign: 'center' }}>
                        {' Right-click this item '}
                    </FluxPane>
                </FluxContextMenu>
            </div>
        </>
    );
}

// docs/code/components/context-menu/finder.vue
<template>
    <div style="display: flex; flex-flow: column; gap: 15px">
        <div style="display: flex; align-items: center; gap: 9px">
            <FluxToggle
                v-model="showCone"/>

            Prediction cone
        </div>

        <FluxContextMenu :debug-cone="showCone">
            <FluxPane style="padding: 36px; text-align: center">
                Right-click this item
            </FluxPane>

            <template #menu="{close}">
                <FluxMenu>
                    <FluxMenuGroup>
                        <FluxMenuItem
                            icon-leading="arrow-up-right-from-square"
                            label="Open"
                            type="button"
                            @click="close"/>

                        <FluxMenuFlyout
                            icon="image"
                            label="Open With">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        icon-leading="eye"
                                        label="Preview"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="image"
                                        label="Photos"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>

                                <FluxSeparator/>

                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        label="App Store…"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>

                        <FluxMenuItem
                            icon-leading="trash"
                            is-destructive
                            label="Move to Trash"
                            type="button"
                            @click="close"/>
                    </FluxMenuGroup>

                    <FluxSeparator/>

                    <FluxMenuGroup>
                        <FluxMenuItem
                            icon-leading="circle-info"
                            label="Get Info"
                            type="button"
                            @click="close"/>

                        <FluxMenuItem
                            icon-leading="pen"
                            label="Rename"
                            type="button"
                            @click="close"/>

                        <FluxMenuItem
                            icon-leading="clone"
                            label="Duplicate"
                            type="button"
                            @click="close"/>

                        <FluxMenuItem
                            icon-leading="eye"
                            label="Quick Look"
                            type="button"
                            @click="close"/>
                    </FluxMenuGroup>

                    <FluxSeparator/>

                    <FluxMenuGroup>
                        <FluxMenuItem
                            icon-leading="copy"
                            label="Copy"
                            type="button"
                            @click="close"/>

                        <FluxMenuFlyout
                            icon="arrow-up-from-square"
                            label="Share">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        icon-leading="paper-plane"
                                        label="Mail"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="copy"
                                        label="Copy Link"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>

                        <FluxMenuFlyout
                            icon="bolt"
                            label="Quick Actions">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        icon-leading="rotate-left"
                                        label="Rotate Left"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="pen"
                                        label="Markup"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="image"
                                        label="Convert Image"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>
                    </FluxMenuGroup>

                    <FluxSeparator/>

                    <FluxMenuGroup>
                        <FluxMenuFlyout
                            icon="palette"
                            label="Tags">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        icon-leading="circle"
                                        label="Red"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="circle"
                                        label="Orange"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="circle"
                                        label="Green"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>

                        <FluxMenuFlyout
                            icon="gear"
                            label="Services">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        label="Show in Enclosing Folder"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        label="New Terminal at Folder"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>
                    </FluxMenuGroup>
                </FluxMenu>
            </template>
        </FluxContextMenu>
    </div>
</template>

<script
    lang="ts"
    setup>
    import { FluxContextMenu, FluxMenu, FluxMenuFlyout, FluxMenuGroup, FluxMenuItem, FluxPane, FluxSeparator, FluxToggle } from '@flux-ui/components';
    import { ref } from 'vue';

    const showCone = ref(false);
</script>
