// docs/code/components/menu/flyout/nested.vue
<template>
    <div style="display: flex; flex-flow: column; gap: 15px">
        <div style="display: flex; align-items: center; gap: 9px">
            <FluxToggle
                v-model="showCone"/>

            Prediction cone
        </div>

        <FluxPane style="width: 300px">
            <FluxMenu :debug-cone="showCone">
                <FluxMenuGroup>
                    <FluxMenuItem
                        icon-leading="pen"
                        label="Edit"/>

                    <FluxMenuFlyout
                        icon="arrow-up-from-square"
                        label="Share">
                        <FluxMenu>
                            <FluxMenuGroup>
                                <FluxMenuItem
                                    icon-leading="paper-plane"
                                    label="Email"/>

                                <FluxMenuFlyout
                                    icon="users"
                                    label="Social">
                                    <FluxMenu>
                                        <FluxMenuGroup>
                                            <FluxMenuItem label="Mastodon"/>

                                            <FluxMenuItem label="Bluesky"/>

                                            <FluxMenuItem label="LinkedIn"/>
                                        </FluxMenuGroup>
                                    </FluxMenu>
                                </FluxMenuFlyout>

                                <FluxMenuItem
                                    icon-leading="copy"
                                    label="Copy link"/>
                            </FluxMenuGroup>
                        </FluxMenu>
                    </FluxMenuFlyout>
                </FluxMenuGroup>
            </FluxMenu>
        </FluxPane>
    </div>
</template>

<script
    lang="ts"
    setup>
    import { FluxMenu, FluxMenuFlyout, FluxMenuGroup, FluxMenuItem, FluxPane, FluxToggle } from '@flux-ui/components';
    import { ref } from 'vue';

    const showCone = ref(false);
</script>

// docs/react-examples/components/menu/flyout/nested.tsx
import { useState } from 'react';
import {
    FluxMenu,
    FluxMenuFlyout,
    FluxMenuGroup,
    FluxMenuItem,
    FluxPane,
    FluxToggle
} from '@flux-ui/react';
export default function Example() {
    const [showCone, setShowCone] = useState(false);
    return (
        <>
            <div style={{ display: 'flex', flexFlow: 'column', gap: '15px' }}>
                <div style={{display: 'flex', alignItems: 'center', gap: 9}}>
                    <FluxToggle checked={showCone} onCheckedChange={setShowCone} />
                    Prediction cone
                </div>
                <FluxPane style={{ width: '300px' }}>
                    <FluxMenu debugCone={showCone}>
                        <FluxMenuGroup>
                            <FluxMenuItem iconLeading={'pen'} label={'Edit'}></FluxMenuItem>
                            <FluxMenuFlyout icon={'arrow-up-from-square'} label={'Share'}>
                                <FluxMenu>
                                    <FluxMenuGroup>
                                        <FluxMenuItem
                                            iconLeading={'paper-plane'}
                                            label={'Email'}
                                        ></FluxMenuItem>
                                        <FluxMenuFlyout icon={'users'} label={'Social'}>
                                            <FluxMenu>
                                                <FluxMenuGroup>
                                                    <FluxMenuItem label={'Mastodon'}></FluxMenuItem>
                                                    <FluxMenuItem label={'Bluesky'}></FluxMenuItem>
                                                    <FluxMenuItem label={'LinkedIn'}></FluxMenuItem>
                                                </FluxMenuGroup>
                                            </FluxMenu>
                                        </FluxMenuFlyout>
                                        <FluxMenuItem
                                            iconLeading={'copy'}
                                            label={'Copy link'}
                                        ></FluxMenuItem>
                                    </FluxMenuGroup>
                                </FluxMenu>
                            </FluxMenuFlyout>
                        </FluxMenuGroup>
                    </FluxMenu>
                </FluxPane>
            </div>
        </>
    );
}
