// docs/code/components/context-menu/nested-formatting.vue
<template>
    <div style="display: flex; flex-flow: column; gap: 15px">
        <div style="display: flex; align-items: center; gap: 9px">
            <FluxToggle
                v-model="showCone"/>

            Prediction cone
        </div>

        <FluxContextMenu :debug-cone="showCone">
            <FluxPane style="padding: 36px; text-align: center">
                Right-click this cell
            </FluxPane>

            <template #menu="{close}">
                <FluxMenu>
                    <FluxMenuGroup>
                        <FluxMenuItem
                            icon-leading="scissors"
                            label="Cut"
                            type="button"
                            @click="close"/>

                        <FluxMenuItem
                            icon-leading="copy"
                            label="Copy"
                            type="button"
                            @click="close"/>

                        <FluxMenuItem
                            icon-leading="paste"
                            label="Paste"
                            type="button"
                            @click="close"/>
                    </FluxMenuGroup>

                    <FluxSeparator/>

                    <FluxMenuGroup>
                        <FluxMenuFlyout
                            icon="plus"
                            label="Insert">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        icon-leading="arrow-up"
                                        label="Row above"
                                        type="button"
                                        @click="close"/>

                                    <FluxMenuItem
                                        icon-leading="arrow-down"
                                        label="Row below"
                                        type="button"
                                        @click="close"/>
                                </FluxMenuGroup>

                                <FluxSeparator/>

                                <FluxMenuGroup>
                                    <FluxMenuFlyout
                                        icon="table-cells"
                                        label="Cells">
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    icon-leading="arrow-right"
                                                    label="Shift right"
                                                    type="button"
                                                    @click="close"/>

                                                <FluxMenuItem
                                                    icon-leading="arrow-down"
                                                    label="Shift down"
                                                    type="button"
                                                    @click="close"/>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>

                        <FluxMenuFlyout
                            icon="font"
                            label="Format">
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuFlyout
                                        icon="hashtag"
                                        label="Number">
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    label="Currency"
                                                    type="button"
                                                    @click="close"/>

                                                <FluxMenuItem
                                                    label="Percent"
                                                    type="button"
                                                    @click="close"/>

                                                <FluxMenuItem
                                                    label="Date"
                                                    type="button"
                                                    @click="close"/>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>

                                    <FluxMenuFlyout
                                        icon="text-height"
                                        label="Text">
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    icon-leading="bold"
                                                    label="Bold"
                                                    type="button"
                                                    @click="close"/>

                                                <FluxMenuItem
                                                    icon-leading="italic"
                                                    label="Italic"
                                                    type="button"
                                                    @click="close"/>
                                            </FluxMenuGroup>

                                            <FluxSeparator/>

                                            <FluxMenuGroup>
                                                <FluxMenuFlyout
                                                    icon="palette"
                                                    label="Color">
                                                    <FluxMenu>
                                                        <FluxMenuGroup>
                                                            <FluxMenuItem
                                                                icon-leading="circle"
                                                                label="Red"
                                                                type="button"
                                                                @click="close"/>

                                                            <FluxMenuItem
                                                                icon-leading="circle"
                                                                label="Green"
                                                                type="button"
                                                                @click="close"/>

                                                            <FluxMenuItem
                                                                icon-leading="circle"
                                                                label="Blue"
                                                                type="button"
                                                                @click="close"/>
                                                        </FluxMenuGroup>
                                                    </FluxMenu>
                                                </FluxMenuFlyout>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </FluxMenuFlyout>
                    </FluxMenuGroup>

                    <FluxSeparator/>

                    <FluxMenuGroup>
                        <FluxMenuItem
                            icon-leading="trash"
                            is-destructive
                            label="Delete row"
                            type="button"
                            @click="close"/>
                    </FluxMenuGroup>
                </FluxMenu>
            </template>
        </FluxContextMenu>
    </div>
</template>

<script
    lang="ts"
    setup>
    import { FluxContextMenu, FluxMenu, FluxMenuFlyout, FluxMenuGroup, FluxMenuItem, FluxPane, FluxSeparator, FluxToggle } from '@flux-ui/components';
    import { ref } from 'vue';

    const showCone = ref(false);
</script>

// docs/react-examples/components/context-menu/nested-formatting.tsx
import { useState } from 'react';
import {
    FluxContextMenu,
    FluxMenu,
    FluxMenuFlyout,
    FluxMenuGroup,
    FluxMenuItem,
    FluxPane,
    FluxSeparator,
    FluxToggle
} from '@flux-ui/react';
export default function Example() {
    const [showCone, setShowCone] = useState(false);
    return (
        <>
            <div style={{ display: 'flex', flexFlow: 'column', gap: '15px' }}>
                <div style={{display: 'flex', alignItems: 'center', gap: 9}}>
                    <FluxToggle checked={showCone} onCheckedChange={setShowCone} />
                    Prediction cone
                </div>
                <FluxContextMenu
                    debugCone={showCone}
                    menu={({ close }) => (
                        <>
                            <FluxMenu>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        iconLeading={'scissors'}
                                        label={'Cut'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuItem
                                        iconLeading={'copy'}
                                        label={'Copy'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                    <FluxMenuItem
                                        iconLeading={'paste'}
                                        label={'Paste'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                </FluxMenuGroup>
                                <FluxSeparator></FluxSeparator>
                                <FluxMenuGroup>
                                    <FluxMenuFlyout icon={'plus'} label={'Insert'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuItem
                                                    iconLeading={'arrow-up'}
                                                    label={'Row above'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                                <FluxMenuItem
                                                    iconLeading={'arrow-down'}
                                                    label={'Row below'}
                                                    type={'button'}
                                                    onClick={close}
                                                ></FluxMenuItem>
                                            </FluxMenuGroup>
                                            <FluxSeparator></FluxSeparator>
                                            <FluxMenuGroup>
                                                <FluxMenuFlyout
                                                    icon={'table-cells'}
                                                    label={'Cells'}
                                                >
                                                    <FluxMenu>
                                                        <FluxMenuGroup>
                                                            <FluxMenuItem
                                                                iconLeading={'arrow-right'}
                                                                label={'Shift right'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                            <FluxMenuItem
                                                                iconLeading={'arrow-down'}
                                                                label={'Shift down'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                        </FluxMenuGroup>
                                                    </FluxMenu>
                                                </FluxMenuFlyout>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                    <FluxMenuFlyout icon={'font'} label={'Format'}>
                                        <FluxMenu>
                                            <FluxMenuGroup>
                                                <FluxMenuFlyout icon={'hashtag'} label={'Number'}>
                                                    <FluxMenu>
                                                        <FluxMenuGroup>
                                                            <FluxMenuItem
                                                                label={'Currency'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                            <FluxMenuItem
                                                                label={'Percent'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                            <FluxMenuItem
                                                                label={'Date'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                        </FluxMenuGroup>
                                                    </FluxMenu>
                                                </FluxMenuFlyout>
                                                <FluxMenuFlyout icon={'text-height'} label={'Text'}>
                                                    <FluxMenu>
                                                        <FluxMenuGroup>
                                                            <FluxMenuItem
                                                                iconLeading={'bold'}
                                                                label={'Bold'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                            <FluxMenuItem
                                                                iconLeading={'italic'}
                                                                label={'Italic'}
                                                                type={'button'}
                                                                onClick={close}
                                                            ></FluxMenuItem>
                                                        </FluxMenuGroup>
                                                        <FluxSeparator></FluxSeparator>
                                                        <FluxMenuGroup>
                                                            <FluxMenuFlyout
                                                                icon={'palette'}
                                                                label={'Color'}
                                                            >
                                                                <FluxMenu>
                                                                    <FluxMenuGroup>
                                                                        <FluxMenuItem
                                                                            iconLeading={'circle'}
                                                                            label={'Red'}
                                                                            type={'button'}
                                                                            onClick={close}
                                                                        ></FluxMenuItem>
                                                                        <FluxMenuItem
                                                                            iconLeading={'circle'}
                                                                            label={'Green'}
                                                                            type={'button'}
                                                                            onClick={close}
                                                                        ></FluxMenuItem>
                                                                        <FluxMenuItem
                                                                            iconLeading={'circle'}
                                                                            label={'Blue'}
                                                                            type={'button'}
                                                                            onClick={close}
                                                                        ></FluxMenuItem>
                                                                    </FluxMenuGroup>
                                                                </FluxMenu>
                                                            </FluxMenuFlyout>
                                                        </FluxMenuGroup>
                                                    </FluxMenu>
                                                </FluxMenuFlyout>
                                            </FluxMenuGroup>
                                        </FluxMenu>
                                    </FluxMenuFlyout>
                                </FluxMenuGroup>
                                <FluxSeparator></FluxSeparator>
                                <FluxMenuGroup>
                                    <FluxMenuItem
                                        iconLeading={'trash'}
                                        isDestructive
                                        label={'Delete row'}
                                        type={'button'}
                                        onClick={close}
                                    ></FluxMenuItem>
                                </FluxMenuGroup>
                            </FluxMenu>
                        </>
                    )}
                >
                    <FluxPane style={{ padding: '36px', textAlign: 'center' }}>
                        {' Right-click this cell '}
                    </FluxPane>
                </FluxContextMenu>
            </div>
        </>
    );
}
