// docs/react-examples/visuals/number-flow/kpi-tile.tsx
import { useState } from 'react';
import { FluxFlex, FluxPane, FluxPaneBody, FluxVisualNumberFlow } from '@flux-ui/react';
import { useEffect } from 'react';
export default function Example() {
    const format: Intl.NumberFormatOptions = {
        style: 'currency',
        currency: 'USD',
        maximumFractionDigits: 0
    };
    const [value, setValue] = useState(84500);
    let timer: number;
    function tick(): void {
        setValue((value) => value + Math.floor(Math.random() * 900));
    }
    useEffect(() => {
        (() => {
            timer = window.setInterval(tick, 2500);
        })();
        return () => (() => window.clearInterval(timer))();
    }, []);
    return (
        <>
            <FluxPane style={{ width: '261px' }}>
                <FluxPaneBody>
                    <FluxFlex align={'start'} direction={'vertical'} gap={3}>
                        <span
                            style={{
                                color: 'var(--foreground-secondary)',
                                fontSize: '13px',
                                fontWeight: '500'
                            }}
                        >
                            {'Monthly revenue'}
                        </span>
                        <FluxVisualNumberFlow
                            format={format}
                            value={value}
                            style={{ fontSize: '33px', fontWeight: '700' }}
                        ></FluxVisualNumberFlow>
                    </FluxFlex>
                </FluxPaneBody>
            </FluxPane>
        </>
    );
}

// docs/code/visuals/number-flow/kpi-tile.vue
<template>
    <FluxPane style="width: 261px;">
        <FluxPaneBody>
            <FluxFlex
                align="start"
                direction="vertical"
                :gap="3">
                <span style="color: var(--foreground-secondary); font-size: 13px; font-weight: 500;">Monthly revenue</span>

                <FluxVisualNumberFlow
                    :format="format"
                    :value="value"
                    style="font-size: 33px; font-weight: 700;"/>
            </FluxFlex>
        </FluxPaneBody>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxFlex, FluxPane, FluxPaneBody } from '@flux-ui/components';
    import { FluxVisualNumberFlow } from '@flux-ui/visuals';
    import { onBeforeUnmount, onMounted, ref } from 'vue';

    const format: Intl.NumberFormatOptions = {style: 'currency', currency: 'USD', maximumFractionDigits: 0};
    const value = ref(84500);

    let timer: number;

    function tick(): void {
        value.value += Math.floor(Math.random() * 900);
    }

    onMounted(() => {
        timer = window.setInterval(tick, 2500);
    });

    onBeforeUnmount(() => window.clearInterval(timer));
</script>
