// docs/react-examples/components/form/date-range/month.tsx
import { type ComponentProps, useState } from 'react';
import { FluxForm, FluxFormDateRangeInput, FluxFormField, FluxPane, FluxPaneBody } from '@flux-ui/react';
import { DateTime } from 'luxon';
export default function Example() {
    const [value, setValue] = useState<Exclude<ComponentProps<typeof FluxFormDateRangeInput>['value'], undefined>>([
        DateTime.now().startOf('month'),
        DateTime.now().endOf('month')
    ]);
    return (<><FluxPane style={{ "maxWidth": "390px" }}><FluxForm><FluxPaneBody><FluxFormField label={"Month"}><FluxFormDateRangeInput value={value} onValueChange={setValue} rangeMode={"month"}></FluxFormDateRangeInput></FluxFormField></FluxPaneBody></FluxForm></FluxPane></>);
}

// docs/code/guide/components/date-picker/month.vue
<template>
    <FluxPane style="width: 330px">
        <FluxDatePicker
            v-model="dates"
            range-mode="month"/>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxDatePicker, FluxPane } from '@flux-ui/flux';
    import { DateTime } from 'luxon';
    import { ref } from 'vue';

    const dates = ref([
        DateTime.now().startOf('month'),
        DateTime.now().endOf('month')
    ]);
</script>
