// docs/react-examples/visuals/slot-text/clock.tsx
import { FluxVisualSlotText } from '@flux-ui/react';
import { useState, useEffect } from 'react';
export default function Example() {
    const [time, setTime] = useState(() =>
        new Date().toLocaleTimeString('en-US', { hour12: false })
    );
    useEffect(() => {
        const timer = setInterval(
            () => setTime(new Date().toLocaleTimeString('en-US', { hour12: false })),
            1000
        );
        return () => clearInterval(timer);
    }, []);
    return (
        <>
            <div
                style={{
                    fontSize: '39px',
                    fontWeight: '700',
                    fontVariantNumeric: 'tabular-nums',
                    letterSpacing: '0.02em'
                }}
            >
                <FluxVisualSlotText direction={'up'} text={time}></FluxVisualSlotText>
            </div>
        </>
    );
}

// docs/code/components/visual/slot-text/clock.vue
<template>
    <FluxSlotText
        direction="up"
        :text="time"
        style="font-size: 39px; font-weight: 700; font-variant-numeric: tabular-nums; letter-spacing: 0.02em;"/>
</template>

<script
    lang="ts"
    setup>
    import { FluxSlotText } from '@flux-ui/components';
    import { onBeforeUnmount, onMounted, ref } from 'vue';

    const time = ref('00:00:00');

    let timer: number;

    function tick(): void {
        time.value = new Date().toLocaleTimeString('en-US', {hour12: false});
    }

    onMounted(() => {
        tick();
        timer = window.setInterval(tick, 1000);
    });

    onBeforeUnmount(() => window.clearInterval(timer));
</script>
