// docs/react-examples/visuals/slot-text/flash.tsx
import { type ComponentRef, useRef } from 'react';
import { FluxSecondaryButton, FluxVisualSlotText } from '@flux-ui/react';
export default function Example() {
    const labelRef = useRef<ComponentRef<typeof FluxVisualSlotText> | null>(null);
    function copy(): void {
        labelRef.current?.flash('Copied', {enter: {direction: 'up'}});
    }
    return <FluxSecondaryButton iconLeading="copy" onClick={copy}>
        <FluxVisualSlotText ref={labelRef} text="Copy"/>
    </FluxSecondaryButton>;
}

// docs/code/components/visual/slot-text/flash.vue
<template>
    <FluxSecondaryButton
        icon-leading="copy"
        @click="copy">
        <template #label>
            <FluxSlotText
                ref="label"
                text="Copy"/>
        </template>
    </FluxSecondaryButton>
</template>

<script
    lang="ts"
    setup>
    import { FluxSecondaryButton, FluxSlotText } from '@flux-ui/components';
    import { useTemplateRef } from 'vue';

    const labelRef = useTemplateRef<InstanceType<typeof FluxSlotText>>('label');

    function copy(): void {
        labelRef.value?.flash('Copied', {enter: {direction: 'up'}});
    }
</script>
