// docs/react-examples/components/menu/control/search.tsx
import { type ComponentProps, useState } from 'react';
import {
    FluxFormInput,
    FluxMenu,
    FluxMenuControl,
    FluxMenuGroup,
    FluxMenuItem,
    FluxMenuSubHeader,
    FluxPane,
    type FluxIconName
} from '@flux-ui/react';
export default function Example() {
    const actions: {
        readonly icon: FluxIconName;
        readonly label: string;
    }[] = [
        { icon: 'scissors', label: 'Cut' },
        { icon: 'copy', label: 'Copy' },
        { icon: 'paste', label: 'Paste' },
        { icon: 'clone', label: 'Duplicate' },
        { icon: 'pen', label: 'Rename' },
        { icon: 'trash', label: 'Delete' }
    ];
    const [query, setQuery] = useState<string>('');
    const filtered = (() =>
        actions.filter((action) => action.label.toLowerCase().includes(query.toLowerCase())))();
    return (
        <>
            <FluxPane style={{ width: '300px' }}>
                <FluxMenu>
                    <FluxMenuControl>
                        <FluxFormInput
                            value={query}
                            onValueChange={(next) => setQuery(String(next ?? ''))}
                            type={'search'}
                            iconLeading={'magnifying-glass'}
                            placeholder={'Filter actions...'}
                        ></FluxFormInput>
                    </FluxMenuControl>
                    <FluxMenuGroup>
                        {filtered.map((action) => (
                            <FluxMenuItem
                                key={action.label}
                                iconLeading={action.icon}
                                label={action.label}
                            ></FluxMenuItem>
                        ))}
                        {filtered.length === 0 ? (
                            <FluxMenuSubHeader label={'No matches'}></FluxMenuSubHeader>
                        ) : null}
                    </FluxMenuGroup>
                </FluxMenu>
            </FluxPane>
        </>
    );
}

// docs/code/components/menu/control/search.vue
<template>
    <FluxPane style="width: 300px">
        <FluxMenu>
            <FluxMenuControl>
                <FluxFormInput
                    v-model="query"
                    type="search"
                    icon-leading="magnifying-glass"
                    placeholder="Filter actions..."/>
            </FluxMenuControl>

            <FluxMenuGroup>
                <FluxMenuItem
                    v-for="action of filtered"
                    :key="action.label"
                    :icon-leading="action.icon"
                    :label="action.label"/>

                <FluxMenuSubHeader
                    v-if="filtered.length === 0"
                    label="No matches"/>
            </FluxMenuGroup>
        </FluxMenu>
    </FluxPane>
</template>

<script
    lang="ts"
    setup>
    import { FluxFormInput, FluxMenu, FluxMenuControl, FluxMenuGroup, FluxMenuItem, FluxMenuSubHeader, FluxPane } from '@flux-ui/components';
    import type { FluxIconName } from '@flux-ui/types';
    import { computed, ref } from 'vue';

    const actions: { readonly icon: FluxIconName; readonly label: string; }[] = [
        {icon: 'scissors', label: 'Cut'},
        {icon: 'copy', label: 'Copy'},
        {icon: 'paste', label: 'Paste'},
        {icon: 'clone', label: 'Duplicate'},
        {icon: 'pen', label: 'Rename'},
        {icon: 'trash', label: 'Delete'}
    ];

    const query = ref('');

    const filtered = computed(() => actions.filter(action => action.label.toLowerCase().includes(query.value.toLowerCase())));
</script>
