// packages/docs/src/code/components/progressBar/snackbar.vue
<template>
    <FluxSnackbar
        is-rendered
        progress-status="Fetching information..."
        :progress-value="0.5"
        icon="arrow-down-to-line"
        message="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer efficitur faucibus tortor, et ornare mauris."
        title="Downloading"/>
</template>

<script
    setup
    lang="ts">
    import { FluxSnackbar } from '@fancee/flux';
</script>

// docs/react-examples/components/progress-bar/snackbar.tsx
import { FluxSnackbar } from '@flux-ui/react';
export default function Example() {
    return (
        <>
            <FluxSnackbar
                progressStatus={'Fetching Flux packages...'}
                progressValue={0.75}
                icon={'arrow-down-to-line'}
                message={'Downloading the new version of Flux.'}
                title={'Flux update'}
            ></FluxSnackbar>
        </>
    );
}
