// docs/code/ai/prompt-input/streaming.vue
<template>
    <FluxAiPromptInput
        v-model="prompt"
        :is-streaming="isStreaming"
        placeholder="Ask a follow-up question..."
        @stop="onStop"
        @submit="onSubmit"/>
</template>

<script
    lang="ts"
    setup>
    import { FluxAiPromptInput } from '@flux-ui/ai';
    import { onUnmounted, ref } from 'vue';

    const isStreaming = ref(false);
    const prompt = ref('');

    let timer: ReturnType<typeof setTimeout> | undefined;

    onUnmounted(() => clearTimeout(timer));

    function onStop(): void {
        clearTimeout(timer);
        isStreaming.value = false;
    }

    function onSubmit(): void {
        prompt.value = '';
        isStreaming.value = true;
        timer = setTimeout(() => isStreaming.value = false, 4000);
    }
</script>

// docs/react-examples/ai/prompt-input/streaming.tsx
import { FluxAiPromptInput } from '@flux-ui/react';
import { useState, useEffect } from 'react';
export default function Example() {
    const [prompt, setPrompt] = useState('');
    const [isStreaming, setStreaming] = useState(false);
    useEffect(() => {
        if (!isStreaming) return;
        const timer = setTimeout(() => setStreaming(false), 4000);
        return () => clearTimeout(timer);
    }, [isStreaming]);
    function onStop() {
        setStreaming(false);
    }
    function onSubmit() {
        setPrompt('');
        setStreaming(true);
    }
    return (
        <>
            <FluxAiPromptInput
                value={prompt}
                onValueChange={setPrompt}
                isStreaming={isStreaming}
                placeholder={'Ask a follow-up question...'}
                onStop={onStop}
                onSubmit={onSubmit}
            ></FluxAiPromptInput>
        </>
    );
}
