// docs/code/components/overflow-bar/with-flyout.vue
<template>
    <FluxPane style="width: min(100%, 480px)">
        <FluxPaneBody>
            <FluxOverflowBar
                alignment="end"
                :gap="9">
                <FluxSecondaryButton
                    v-for="label in buttons"
                    :key="label"
                    :label="label"/>

                <template #overflow="{ items }">
                    <FluxFlyout v-if="items.length > 0">
                        <template #opener="{toggle}">
                            <FluxSecondaryButton
                                :label="`+${items.length} more`"
                                @click="toggle"/>
                        </template>

                        <FluxMenu>
                            <component
                                :is="item"
                                v-for="(item, index) in items"
                                :key="index"/>
                        </FluxMenu>
                    </FluxFlyout>
                </template>
            </FluxOverflowBar>
        </FluxPaneBody>
    </FluxPane>
</template>

<script
    setup
    lang="ts">
    import { FluxFlyout, FluxMenu, FluxOverflowBar, FluxPane, FluxPaneBody, FluxSecondaryButton } from '@flux-ui/components';

    const buttons = ['Export', 'Import', 'Duplicate', 'Archive', 'Delete', 'Share', 'Print'];
</script>

// docs/react-examples/components/overflow-bar/with-flyout.tsx
import { Fragment } from 'react';
import {
    FluxFlyout,
    FluxMenu,
    FluxOverflowBar,
    FluxPane,
    FluxPaneBody,
    FluxSecondaryButton
} from '@flux-ui/react';
export default function Example() {
    const buttons = ['Export', 'Import', 'Duplicate', 'Archive', 'Delete', 'Share', 'Print'];
    return (
        <>
            <FluxPane style={{ width: 'min(100%, 480px)' }}>
                <FluxPaneBody>
                    <FluxOverflowBar
                        alignment={'end'}
                        gap={9}
                        overflow={({ items }) => (
                            <>
                                {items.length > 0 ? (
                                    <FluxFlyout
                                        opener={({ toggle }) => (
                                            <>
                                                <FluxSecondaryButton
                                                    label={`+${items.length} more`}
                                                    onClick={toggle}
                                                ></FluxSecondaryButton>
                                            </>
                                        )}
                                    >
                                        {() => (
                                            <>
                                                <FluxMenu>
                                                    {items.map((item, index) => (
                                                        <Fragment key={index}>{item}</Fragment>
                                                    ))}
                                                </FluxMenu>
                                            </>
                                        )}
                                    </FluxFlyout>
                                ) : null}
                            </>
                        )}
                    >
                        {buttons.map((label) => (
                            <FluxSecondaryButton key={label} label={label}></FluxSecondaryButton>
                        ))}
                    </FluxOverflowBar>
                </FluxPaneBody>
            </FluxPane>
        </>
    );
}
