// docs/react-examples/components/sheet/scrollable.tsx
import { useState } from 'react';
import {
    FluxItem,
    FluxItemActions,
    FluxItemContent,
    FluxItemStack,
    FluxPane,
    FluxPaneFooter,
    FluxPaneHeader,
    FluxSecondaryButton,
    FluxSheet,
    FluxSpacer
} from '@flux-ui/react';
export default function Example() {
    const orders = Array.from({ length: 24 }, (_, index) => ({
        id: `#${4820 - index}`,
        date: `March ${((index * 3) % 28) + 1}, 2025`,
        total: `€ ${(19 + index * 7).toFixed(2)}`
    }));
    const [isSheetOpened, setIsSheetOpened] = useState(false);
    return (
        <>
            <FluxSecondaryButton
                iconLeading={'list-ul'}
                label={'Order history'}
                onClick={() => {
                    setIsSheetOpened(true);
                }}
            ></FluxSecondaryButton>
            <FluxSheet
                snapPoints={[.5, .95]}
                isCloseable
                onClose={() => {
                    setIsSheetOpened(false);
                }}
                open={isSheetOpened}
            >
                {isSheetOpened ? (
                    <FluxPane>
                        <FluxPaneHeader title={'Order history'}></FluxPaneHeader>
                        <FluxItemStack>
                            {orders.map((order) => (
                                <FluxItem key={order.id}>
                                    <FluxItemContent>
                                        <strong>{order.id}</strong>
                                        <span style={{ fontSize: '.875rem', opacity: '.6' }}>
                                            {order.date}
                                        </span>
                                    </FluxItemContent>
                                    <FluxItemActions isCenter>
                                        <span>{order.total}</span>
                                    </FluxItemActions>
                                </FluxItem>
                            ))}
                        </FluxItemStack>
                        <FluxPaneFooter>
                            <FluxSpacer></FluxSpacer>
                            <FluxSecondaryButton
                                label={'Close'}
                                onClick={() => {
                                    setIsSheetOpened(false);
                                }}
                            ></FluxSecondaryButton>
                        </FluxPaneFooter>
                    </FluxPane>
                ) : null}
            </FluxSheet>
        </>
    );
}

// docs/code/components/sheet/scrollable.vue
<template>
    <FluxSecondaryButton
        icon-leading="list-ul"
        label="Order history"
        @click="isSheetOpened = true"/>

    <FluxSheet
        is-closeable
        :snap-points="[.5, .95]"
        @close="isSheetOpened = false">
        <FluxPane v-if="isSheetOpened">
            <FluxPaneHeader title="Order history"/>

            <FluxItemStack>
                <FluxItem
                    v-for="order of orders"
                    :key="order.id">
                    <FluxItemContent>
                        <strong>{{ order.id }}</strong>
                        <span style="font-size: .875rem; opacity: .6">{{ order.date }}</span>
                    </FluxItemContent>

                    <FluxItemActions is-center>
                        <span>{{ order.total }}</span>
                    </FluxItemActions>
                </FluxItem>
            </FluxItemStack>

            <FluxPaneFooter>
                <FluxSpacer/>

                <FluxSecondaryButton
                    label="Close"
                    @click="isSheetOpened = false"/>
            </FluxPaneFooter>
        </FluxPane>
    </FluxSheet>
</template>

<script
    setup
    lang="ts">
    import { FluxItem, FluxItemActions, FluxItemContent, FluxItemStack, FluxPane, FluxPaneFooter, FluxPaneHeader, FluxSecondaryButton, FluxSheet, FluxSpacer } from '@flux-ui/components';
    import { ref } from 'vue';

    const orders = Array.from({length: 24}, (_, index) => ({
        id: `#${4820 - index}`,
        date: `March ${((index * 3) % 28) + 1}, 2025`,
        total: `€ ${(19 + index * 7).toFixed(2)}`
    }));

    const isSheetOpened = ref(false);
</script>
