// docs/react-examples/components/progress-bar/complete.tsx
import { FluxPane, FluxPaneBody, FluxProgressBar } from '@flux-ui/react';
import { useEffect, useState } from 'react';
export default function Example() {
    const [value, setValue] = useState(0);
    const [status, setStatus] = useState('Preparing...');
    useEffect(() => {
        const start = performance.now();
        const timer = setInterval(() => {
            const phase = (performance.now() - start) % 6500;
            const progress = Math.min(Math.max((phase - 600) / 4200, 0), 1);
            setValue(progress);
            setStatus(
                phase < 600
                    ? 'Preparing...'
                    : progress < 0.7
                      ? 'Downloading...'
                      : progress < 1
                        ? 'Unzipping...'
                        : 'Done.'
            );
        }, 50);
        return () => clearInterval(timer);
    }, []);
    return (
        <>
            <FluxPane>
                <FluxPaneBody>
                    <FluxProgressBar status={status} value={value}></FluxProgressBar>
                </FluxPaneBody>
            </FluxPane>
        </>
    );
}

// docs/code/components/progress-bar/complete.vue
<template>
    <FluxPane>
        <FluxPaneBody>
            <FluxProgressBar
                :status="status"
                :value="value"/>
        </FluxPaneBody>
    </FluxPane>
</template>

<script
    setup
    lang="ts">
    import { FluxPane, FluxPaneBody, FluxProgressBar } from '@flux-ui/components';
    import { onMounted, onUnmounted, ref, unref } from 'vue';

    const timer = ref<NodeJS.Timeout>();
    const status = ref('Preparing...');
    const value = ref(0);

    onMounted(async () => await playbook());
    onUnmounted(() => clearTimeout(unref(timer)));

    async function playbook(): Promise<void> {
        status.value = 'Preparing...';
        value.value = 0;

        await wait(600);
        await tween(0.2);

        status.value = 'Downloading...';
        await wait(300);
        await tween(0.7);

        status.value = 'Unzipping...';
        await wait(600);
        await tween(1);

        status.value = 'Done.';

        await wait(1500);
        requestAnimationFrame(playbook);
    }

    async function tween(percentage: number): Promise<void> {
        for (let p = unref(value); p <= percentage; p += 0.001) {
            value.value = p;
            await wait(Math.random() * 6 + 3);
        }

        value.value = percentage;
    }

    async function wait(ms: number): Promise<void> {
        await new Promise(resolve => timer.value = setTimeout(resolve, ms));
    }
</script>
