// docs/react-examples/components/progress-bar/snackbar.tsx
import { FluxSnackbar } from '@flux-ui/react';
export default function Example() {
    return (
        <>
            <FluxSnackbar
                progressStatus={'Fetching Flux packages...'}
                progressValue={0.75}
                icon={'arrow-down-to-line'}
                message={'Downloading the new version of Flux.'}
                title={'Flux update'}
            ></FluxSnackbar>
        </>
    );
}

// docs/code/components/progress-bar/snackbar.vue
<template>
    <FluxSnackbar
        is-rendered
        progress-status="Fetching Flux packages..."
        :progress-value="0.75"
        icon="arrow-down-to-line"
        message="Downloading the new version of Flux."
        title="Flux update"/>
</template>

<script
    setup
    lang="ts">
    import { FluxSnackbar } from '@flux-ui/components';
</script>
